"""add_notification_prefs_to_users

Revision ID: 0d7b9b48c634
Revises: a61203019b81
Create Date: 2026-03-01 20:42:01.142994

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0d7b9b48c634'
down_revision: str | None = 'a61203019b81'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_approval_tasks_due_at', table_name='approval_tasks')
    op.drop_index('ix_approval_tasks_status_due_at', table_name='approval_tasks')
    op.drop_index('ix_audit_logs_entity_id_created_at', table_name='audit_logs')
    op.drop_index('ix_exceptions_status_severity', table_name='exception_records')
    op.drop_index('ix_invoices_created_at', table_name='invoices')
    op.drop_index('ix_invoices_due_date', table_name='invoices')
    op.drop_index('ix_invoices_payment_status', table_name='invoices')
    op.drop_index('ix_invoices_status', table_name='invoices')
    op.drop_index('ix_invoices_status_created_at', table_name='invoices')
    op.add_column('sla_alerts', sa.Column('description', sa.String(length=500), nullable=False))
    op.add_column('sla_alerts', sa.Column('status', sa.String(length=50), nullable=False))
    op.alter_column('sla_alerts', 'alert_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index('ix_sla_alerts_alert_date', table_name='sla_alerts')
    op.drop_index('ix_sla_alerts_alert_type', table_name='sla_alerts')
    op.drop_column('sla_alerts', 'days_until_due')
    op.drop_column('sla_alerts', 'due_date')
    op.drop_column('sla_alerts', 'invoice_status')
    op.drop_column('sla_alerts', 'resolved')
    op.drop_column('sla_alerts', 'alert_date')
    op.drop_column('sla_alerts', 'notes')
    op.alter_column('users', 'deleted_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using='deleted_at::timestamp with time zone')
    op.add_column('users', sa.Column('notification_prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('ix_vendor_messages_invoice_direction', table_name='vendor_messages')
    op.drop_constraint('uq_vendor_risk_scores_vendor_id', 'vendor_risk_scores', type_='unique')
    op.drop_index('ix_vendor_risk_scores_vendor_id', table_name='vendor_risk_scores')
    op.create_index(op.f('ix_vendor_risk_scores_vendor_id'), 'vendor_risk_scores', ['vendor_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_risk_scores_vendor_id'), table_name='vendor_risk_scores')
    op.create_index('ix_vendor_risk_scores_vendor_id', 'vendor_risk_scores', ['vendor_id'], unique=False)
    op.create_unique_constraint('uq_vendor_risk_scores_vendor_id', 'vendor_risk_scores', ['vendor_id'])
    op.create_index('ix_vendor_messages_invoice_direction', 'vendor_messages', ['invoice_id', 'direction'], unique=False)
    op.drop_column('users', 'notification_prefs')
    op.alter_column('users', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('sla_alerts', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sla_alerts', sa.Column('alert_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('sla_alerts', sa.Column('resolved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('sla_alerts', sa.Column('invoice_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('sla_alerts', sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('sla_alerts', sa.Column('days_until_due', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_sla_alerts_alert_type', 'sla_alerts', ['alert_type'], unique=False)
    op.create_index('ix_sla_alerts_alert_date', 'sla_alerts', ['alert_date'], unique=False)
    op.alter_column('sla_alerts', 'alert_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('sla_alerts', 'status')
    op.drop_column('sla_alerts', 'description')
    op.create_index('ix_invoices_status_created_at', 'invoices', ['status', 'created_at'], unique=False)
    op.create_index('ix_invoices_status', 'invoices', ['status'], unique=False)
    op.create_index('ix_invoices_payment_status', 'invoices', ['payment_status'], unique=False)
    op.create_index('ix_invoices_due_date', 'invoices', ['due_date'], unique=False)
    op.create_index('ix_invoices_created_at', 'invoices', ['created_at'], unique=False)
    op.create_index('ix_exceptions_status_severity', 'exception_records', ['status', 'severity'], unique=False)
    op.create_index('ix_audit_logs_entity_id_created_at', 'audit_logs', ['entity_id', 'created_at'], unique=False)
    op.create_index('ix_approval_tasks_status_due_at', 'approval_tasks', ['status', 'due_at'], unique=False)
    op.create_index('ix_approval_tasks_due_at', 'approval_tasks', ['due_at'], unique=False)
    # ### end Alembic commands ###
