"""add_payment_runs

Revision ID: ac340ecf38cf
Revises: acd0a0c1388e
Create Date: 2026-03-01 22:40:41.575393

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ac340ecf38cf'
down_revision: str | None = 'acd0a0c1388e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_runs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('invoice_count', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_runs_vendor_id'), 'payment_runs', ['vendor_id'], unique=False)
    op.add_column('invoices', sa.Column('payment_run_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_invoices_payment_run_id'), 'invoices', ['payment_run_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'payment_runs', ['payment_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_payment_run_id'), table_name='invoices')
    op.drop_column('invoices', 'payment_run_id')
    op.drop_index(op.f('ix_payment_runs_vendor_id'), table_name='payment_runs')
    op.drop_table('payment_runs')
    # ### end Alembic commands ###
